### ISSUE TITLE
Video watch page is broken

### ISSUE THREAD

**Issue by Tippon** [taylorbobaylor/TrailerDownloader#14]
Hi :)

I've just tried to use the Windows version, and I can't get it to download any trailers. 

I've extracted the zip, run the file, and opened a browser to the page. So far, so good. I put in my movie folder and it correctly identifies the movies without trailers. I selected a few, and clicked download selected trailers, but got the error starting Issues downloading trailers.

I tried moving the movie to a new folder named E:\Movies, to match your example, and got the same problem. The movie is Adventures of Rufus - The Fantastic Pet (2020) and the folder has the same name, so E:\Movies\Adventures of Rufus - The Fantastic Pet (2020)\Adventures of Rufus - The Fantastic Pet (2020).mkv (I know, I should have picked a shorter name!). I'm getting

```
Fail: TrailerDownloader.SignalRHubs.MovieHub[0]
Error downloading trailer for Adventures of Rufus - The Fantastic Pet
Video watch page is broken.
In most cases, this indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
```

I tried searching youtube for the trailer, and the first result is the official trailer, and it plays perfectly. I get the same error for Luca and Batman: The Long Halloween.

Thanks for any help :)

**Comment by taylorbobaylor** [comment]
Hey! Sorry, I've been crazy busy at work. I actually have Luca as well in my library and it didn't have any issues downloading the trailer. I will try to look at this and replicate the issue locally when I can find some time. Sorry you're having issues with it but hopefully we can get it resolved for you. 😃

**Comment by taylorbobaylor** [comment]
I just tried to replicate this and am not seeing any issues. My folder name is Adventures of Rufus - The Fantastic Pet (2020) and my file name is Adventures of Rufus - The Fantastic Pet (2020).mkv.
It is working for Luca as well. Can you provide any more information on how to replicate this?
![image](https://user-images.githubusercontent.com/25238885/123518037-380e2900-d672-11eb-9d79-967ec2d58265.png)

**Comment by Tippon** [comment]
Hi Taylor :)

Thanks for replying. Apologies for the slow reply :)

This may be a problem on my end. I found out yesterday that my media computer is inconsistently having trouble with 127.0.0.1 and localhost, Any programs that use them are having problems. For example, Plex is running and serving existing videos, but can't access its settings or backend.

I'll mark this as closed for now and try your trailer downloader again once everything's working properly on my end.

Thanks for your help :)

**Comment by taylorbobaylor** [comment]
No problem at all, anytime! 😃
