### ISSUE TITLE
Error downloading some trailers

### ISSUE THREAD

**Issue by 924312** [taylorbobaylor/TrailerDownloader#15]
First of all - great work, loving this and it's very handy. 
I'm getting an error for some trailers and it tells me to check the logs but I can't find any? 
I'm using the latest release for Windows
Also, is it using your TMDB API key or do we put our own in there somewhere?

**Comment by taylorbobaylor** [comment]
Thanks so much! If you're running the windows exe it should open and command prompt when you first run it. That's where it's logging out to.

**Comment by 924312** [comment]
Cheers for the quick response, I can't believe I didn't think to check
there 😅

Op ma 4 okt. 2021 om 13:03 schreef Taylor Christian <
***@***.***>:

**Comment by taylorbobaylor** [comment]
No problem at all!
