### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Ozzie19** [taylorbobaylor/TrailerDownloader#22]
Sorry to bother you but every time I run the .exe there is no issue, and then I enter the file directory for my movies. This directory has over 150 films, and every time I enter this directory in the terminal window crashes and the localhost stops responding. Am I doing something wrong or am I trying to force it to do more than it can handle? 
Thanks

**Comment by taylorbobaylor** [comment]
It should be able to handle way more than that. Can you show me the logs when it crashes?

**Comment by Ozzie19** [comment]
Yep no problem.
Sorry might sound stupid but where would I find the log?

**Comment by taylorbobaylor** [comment]
Haha no worries! It should be in the console that comes up when you run the exe

**Comment by Ozzie19** [comment]
Thanks haha.
I start up the application and the four info lines appear, but after that nothing else. As soon as I enter the information onto the online portal the console closes so I can't tell of anything else appears.
The picture attached is all I see.
 ![Screenshot_20220604-172853_Remote Desktop.jpg](https://user-images.githubusercontent.com/61351058/172016273-f803d24f-1af5-4bfd-8163-a2b19f13504c.jpg)

**Comment by taylorbobaylor** [comment]
Hmmmmmmm.... What are you entering in the setup screen?

**Comment by Ozzie19** [comment]
The path to the directory which is located on the G drive, and for the language, I've tried entering the "en-US" and leaving it blank.

Its also worth mentioning a few times that I've done it it's pulled up a list of the movies but nothing else appears in the console and when I attempt to download the trailers for even just 1 the console dissapears again.

**Comment by taylorbobaylor** [comment]
Is G drive a network drive? So sometimes it does load the movies with the posters and sometimes not?

**Comment by Ozzie19** [comment]
Yes I believe it is, I've mounted G drive as a shared drive as I use it directly for my emby server but it is physically connected to my pc.

The thing with the posters sometimes loading and not is true also.

**Comment by taylorbobaylor** [comment]
I can add some more error handling later on and you can try that version to see if we can find the problem. Might not be till tomorrow or later in the week. 
Never seen this issue so not sure what's happening.

**Comment by Ozzie19** [comment]
Thank you, that would be very kind. Honestly take as much time as needed, I don't mean to create an issue for you as I know its more likely me doing something wrong and your time is valuable.

**Comment by taylorbobaylor** [comment]
No worries at all! I enjoy this 😀

**Comment by Ozzie19** [comment]
I've managed to get them running side by side and take a quick print screen when something showed up in the log this time. but unfortunately it dissapears too quick for me to be able to copy and paste it. Hope this help
![Capture](https://user-images.githubusercontent.com/61351058/172025342-9170b72b-e95a-4050-b118-dae7db516c6d.PNG)
s

**Comment by taylorbobaylor** [comment]
Nice! I'll check later when I'm home but looks like some Regex error when parsing through all the movies.

**Comment by taylorbobaylor** [comment]
It's having trouble getting the title of one of the movies. Are all your movies named in same format and can you provide an example?

**Comment by Ozzie19** [comment]
![image](https://user-images.githubusercontent.com/61351058/172026024-3c9eb99d-09f4-4331-a22e-cbdbdea7ad32.png)
Took a quick snapshot of some of the films, not all in the exact same name format but pretty similar. Not sure if that's the issue or if it's a specific folder.

**Comment by taylorbobaylor** [comment]
Yeah with Radarr you can rename all your folders and files like they need to be. But I can add some error handling so we can see which exact file is causing the issue. It's one of the files not the directory that's causing the issue I believe.

**Comment by taylorbobaylor** [comment]
I think I was able to replicate this by removing a movie from a directory and then having some other non media file type in the directory. I added some error handling that should log out the directory if you could give this one a try?
[Preview Release](https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/untagged-9762f6e0b3824f34e88c)

**Comment by Ozzie19** [comment]
Happy to try it out - preview release is returning an error 404 however.

**Comment by Ozzie19** [comment]
Thanks so much. As expected, the issue was of my own doing and your error checking sussed it out for me. I had 2 duplicate folders of the same movie, but one had no content in it - must've been a shell of a failed download. I have now corrected this and the program is working excellently. 

Thanks very much again.

**Comment by taylorbobaylor** [comment]
Glad we got it working! Enjoy 😀
