### ISSUE TITLE
I'm guessing Themoviedb token has expired

### ISSUE THREAD

**Issue by multifrag** [taylorbobaylor/TrailerDownloader#27]
All the trailer download attempts fail. Is there a way to fix it?

Edit: Probably on youtube end, as doing it manually works

**Comment by taylorbobaylor** [comment]
@multifrag - Can you test [this image](https://hub.docker.com/layers/taylorbobaylor/movie-trailer-downloader/latest/images/sha256-32e883198ad356e4f798841c13617715ea98fe3f693aa89ca0d5e121bdddfbe1?context=repo)? I upgraded some of the packages and I'm not seeing any issues with it now.

**Comment by multifrag** [comment]
@taylorbobaylor  
Sorry, I wasn't running it in a docker container but as the windows executable.

**Comment by taylorbobaylor** [comment]
Gotcha, can you try [this](https://github.com/taylorbobaylor/TrailerDownloader/releases/latest)?

**Comment by multifrag** [comment]
@taylorbobaylor 
The downloading works, unfortunately it only detects the film that have sequels. For example Films\The Lord of The Rings Triology\ 3 films folders that have been detected.

All non sequel films like Films\A Quiet Place (2018)\ film file

So this version wants the films to be nested twice

**Comment by taylorbobaylor** [comment]
Ahhhhh okay. I'll look into it sometime this week and fix the scanning of the folders.

**Comment by multifrag** [comment]
@taylorbobaylor Thank you for the tool. Helped a lot

**Comment by taylorbobaylor** [comment]
Awesome, glad to hear! Hopefully will have something for you to test soon.

**Comment by taylorbobaylor** [comment]
Could you try [this](https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/v1.1.5) one and see if it works for you?

**Comment by multifrag** [comment]
@taylorbobaylor All works :) Just took couple refreshes to for all the films to appear(~500). 

The only problem I found was on themoviedb side. When it has no reference to a trailer. Command line gives no error that it couldn't find one. But it's a minor inconvenience just scrolling through the web page.

**Comment by taylorbobaylor** [comment]
@multifrag Nice! Glad we got it working. Yeah.... I want to go back through and refactor the whole thing at some point.... Just need to find the time 😛
