### ISSUE TITLE
"standard_init_linux.go:211: exec user process caused "exec format error""

### ISSUE THREAD

**Issue by marck479** [taylorbobaylor/TrailerDownloader#3]
After deploying the Docker Container I am receiving the message above.
During my research I found out that it is due to different architectures. However, I already run other Docker Containers with the same architecture. What can I do here ?
Could this error possible appear cause the port 80 is already in use?

Thanks a lot in advance!

**Comment by taylorbobaylor** [comment]
Hello! Can you paste the docker command you're running? If you have another container already on port 80 you will have to choose a different one.

**Comment by marck479** [comment]
Thats strange. I thought I change the port by changing it in the comment...
The comment I've run is the following:
docker run -d \
  --name=movie-trailer-downloader \
  -p 6767:6767 \
  -v /media/Drive:/movies \
  taylorbobaylor/movie-trailer-downloader

**Comment by taylorbobaylor** [comment]
Can you delete any containers that it's already created and try this
```
-p 6767:80
```

**Comment by marck479** [comment]
I did.
I get this outcome again:
"standard_init_linux.go:211: exec user process caused "exec format error""

**Comment by taylorbobaylor** [comment]
Could you try running this and paste the output here?
```
docker run -it -p 6767:80 -v /media/Drive:/movies taylorbobaylor/movie-trailer-downloader
```

**Comment by marck479** [comment]
Output:
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by taylorbobaylor** [comment]
What OS are you running exactly?

**Comment by marck479** [comment]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by taylorbobaylor** [comment]
Yeah I'm thinking it won't be able to run on there it looks like if I'm reading [this ](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/4558)right....    😢

**Comment by marck479** [comment]
As i mentioned on the beginning I have already seen such errors and the explanations.
But somehow the other Docker is running properly. For example..
This docker "bubuntux/nordvpn:3.7.4" is the same architecture and it works flawlessly.
Thats really strange.

**Comment by taylorbobaylor** [comment]
Hmmmmmm... When I have some time I'll try to install a VM or something with the same OS and see what I can do... Sorry you're having issues with it...

**Comment by marck479** [comment]
Alright.. Thank you for your REALLY FAST assistance and thank you for providing these plugin to us! 

I heard something of https://docs.docker.com/buildx/working-with-buildx/ 
This is a tool to run a dockerfile in different architectures. But  I didn't really got time to take a deeper look. Maybe this could solve my problem.

I will just stay tuned and and hope to hear from you soon.
Thanks alot!

**Comment by taylorbobaylor** [comment]
No worries at all! Hopefully we'll be able to figure it out one way or another! Do you have a 64 bit environment you could test it out on as well by chance?

**Comment by taylorbobaylor** [comment]
Hey! I just updated the app to .NET 5 which I think has more support for that. Can you try pulling the new image and then run your docker run command again and let me know if that works?
```
docker pull taylorbobaylor/movie-trailer-downloader
```

**Comment by marck479** [comment]
standard_init_linux.go:211: exec user process caused "exec format error"
I did try it with both 6767:80 and 6767:6767

**Comment by taylorbobaylor** [comment]
Ughhhhhh, great... Still haven't had time to setup a VM or anything to test locally. Maybe later I'll try to publish locally for linux-arm and you can build a dockerfile locally and we can try that. I'll let you know. Sorry it's still not working....

**Comment by taylorbobaylor** [comment]
Okay, can you try unzipping this and putting on your machine and then go into that directory and run:
[test.zip](https://github.com/taylorbobaylor/TrailerDownloader/files/5669243/test.zip)
```
docker build .
```
At the end you should get an output similar to:
```
Successfully built 4a961767403d
```
Then try running something like this:
```
docker run -it -p 6767:80 -v /media/Drive:/movies 4a961767403d
```

**Comment by marck479** [comment]
Oh, I am sorry. I already fell asleep yesterday..
The machine seems to run flawlessly. Thats awesome!

But now I get a HTTP-Error trying to access the site with IP:6767
"HTTP ERROR 500"

**Comment by taylorbobaylor** [comment]
Great! Getting a little closer it sounds 😊 
Hmmmmm..... What's the run command you're using now and could you try with http://IP:6767?

**Comment by marck479** [comment]
Yeah i did already to access this link.
Then the error shows up. And I used the command u provided:
docker run -d -p 6767:80 -v /media/Drive:/movies XXXXXXXX

**Comment by taylorbobaylor** [comment]
So, it let you create the container and it's running now, correct? And can you put in a screenshot of the error you're getting and maybe the logs from the container?

**Comment by marck479** [comment]
I couldnt upload the screenshot...
https://ibb.co/MPcdL4S

And i cant upload the logs too...
https://wetransfer.com/downloads/670a362ab9cd9789f02bdbc158cae1ef20201210205234/e93c6b8ceadd58ae191f25e989f69dc720201210205253/03af5b

**Comment by taylorbobaylor** [comment]
Thanks! I think I see the problem now. Can you remove that container and that image and try again with this zip file?
[TrailerDownloaderARM.zip](https://github.com/taylorbobaylor/TrailerDownloader/files/5675807/TrailerDownloaderARM.zip)

**Comment by marck479** [comment]
Oh okay.. looks better.
But now I can't see any stuff and the button for download is unclickable even tho there is stuff in the folder.

https://ibb.co/NNJbW7r

**Comment by marck479** [comment]
And after a while it crashes throwing this error


warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60],
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.,
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35],
      No XML encryptor configured. Key {e5a9ce71-a8aa-4998-b98e-c73498c0a01a} may be persisted to storage in unencrypted form.,
info: Microsoft.Hosting.Lifetime[0],
      Now listening on: http://[::]:80,
info: Microsoft.Hosting.Lifetime[0],
      Application started. Press Ctrl+C to shut down.,
info: Microsoft.Hosting.Lifetime[0],
      Hosting environment: Production,
info: Microsoft.Hosting.Lifetime[0],
      Content root path: /app,
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3],
      Failed to determine the https port for redirect.,
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input'),
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg),
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement),
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement),
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 84,
   at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 51,
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state),
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi),
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state),
   at System.Threading.QueueUserWorkItemCallback.Execute(),
   at System.Threading.ThreadPoolWorkQueue.Dispatch(),
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(),

**Comment by taylorbobaylor** [comment]
It looks like it's not showing any movies from the folder you mounted. Are your movies in the specific naming convention that the app relies on. And if so, you can exec into the docker container and make sure that the folder you mounted has your movies. Inside the docker container they should be stored inside the /movies folder.

**Comment by marck479** [comment]
Yes, the files are there. 
I guess I have some naming problems with the movies then.. I will take a look at it.
We can consider this issue as fixed.
Thanks alot!

**Comment by taylorbobaylor** [comment]
Awesome, glad we got it working! 😊
