### ISSUE TITLE
Error 400 - New error that I am getting

### ISSUE THREAD

**Issue by tudorica12345** [taylorbobaylor/TrailerDownloader#37]
So this is the error that shows up: "Report status code does not indicate success: 400 (bad request)"

I have not seen this one before

**Comment by Fighting40** [comment]
I am getting it as well

**Comment by taylorbobaylor** [comment]
Hey @Fighting40 and @tudorica12345 - Can you try with the [newest release](https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/v1.1.8) and let me know if that works for you?
Thanks! 😊

**Comment by Fighting40** [comment]
Yes, the update fixed the issue I was having. Thank you for your hard work!

**Comment by taylorbobaylor** [comment]
No worries at all, glad it's working! 🤓
