### ISSUE TITLE
Add ARM64 docker image

### ISSUE THREAD

**Issue by felipemarinho97** [taylorbobaylor/TrailerDownloader#42]

**Comment by taylorbobaylor** [comment]
There is one: https://hub.docker.com/layers/taylorbobaylor/movie-trailer-downloader/arm64/images/sha256-8d3f7fa7feb6855f3f0c5e6da203151dd4476a7b7c56caf8b5ba22118bf59141?context=explore

**Comment by felipemarinho97** [comment]
I was getting this error because there is no arm64 for the latest tag:
Pulling trailer-downloader (taylorbobaylor/movie-trailer-downloader:)...
latest: Pulling from taylorbobaylor/movie-trailer-downloader
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by taylorbobaylor** [comment]
Ah gotcha. Can you use the other image for now? Not much has changed between the versions. I'm having issues with the GitHub Actions to build the arm64 version.

**Comment by felipemarinho97** [comment]
Sure, no problems!
