### ISSUE TITLE
New release fails on windows

### ISSUE THREAD

**Issue by multifrag** [taylorbobaylor/TrailerDownloader#43]
Fails to load, also was missing wwwroot fodler but I found it in the previous release.
![image_2024-04-07_230602660](https://github.com/taylorbobaylor/TrailerDownloader/assets/7545135/8b2befad-354f-4da9-a10c-34d9f716d973)

**Comment by simonsteyn** [comment]
New user, same issue here :(

**Comment by taylorbobaylor** [comment]
Hey @multifrag / @simonsteyn - Sorry about that! Can you try this one I just updated [here](https://github.com/taylorbobaylor/TrailerDownloader/releases/download/v1.1.8/TrailerDownloaderWindows.zip)

**Comment by simonsteyn** [comment]
![Trailer Download Error](https://github.com/taylorbobaylor/TrailerDownloader/assets/90009587/2503d337-ff7e-420e-a8d6-e83217bc8aae)

Any reason for this? I know some of the files are not according to the structure it needs to be, but only one movie is recognized. I have multiple movies under the new naming scheme.

**Comment by taylorbobaylor** [comment]
Looks like it's because your files are not in the right convention like you said. Other than than that can't say 100% without logs or something. Anything showing in the console window?

**Comment by simonsteyn** [comment]
Is this naming scheme correct?
Folder:
The Hunger Games The Ballad Of Songbirds Snakes (2023) [1080p] [WEBRip] [5.1]
File:
The Hunger Games The Ballad of Songbirds & Snakes.2023.WEBRip-1080p.AAC.5.1.mp4

**Comment by taylorbobaylor** [comment]
@simonsteyn Any errors in the logs that show up in the console or anything? Do you use Radarr? There's an option in there to rename all your files/folders with this structure. Hopefully in the refactored version the structure won't be forced to a certain format.
