### ISSUE TITLE
Not downloading trailers

### ISSUE THREAD

**Issue by tripelbit-dev** [taylorbobaylor/TrailerDownloader#5]
When I run the app on a fairly large library (1000+ folders), it correctly identifies which folders don't have trailers. 

The first time I click "Download all missing trailers" it indicates a few trailer that it's downloading in the green popup alert.
But it's not downloading a lot of the remaining missing trailers.

If I relaunch the app and click "Download all missing trailers" it doesn't do anything. It just shows "Starting download of all trailers" and "Done downloading all missing trailers" at the same time. But there are still 50+ missing trailers.

![image](https://user-images.githubusercontent.com/56480385/106904570-5a0a0d80-66c9-11eb-9094-e7821c07bc22.png)

Any way to show more info/debug? I've checked the app console but it just shows `Successfully downloaded all missing trailers!`

**Comment by taylorbobaylor** [comment]
Hmmmm.... There should be more logging if it was erroring out for any reason. When I look at the other bug I'll see if I can maybe add some more logging before downloading each trailer or something.

**Comment by taylorbobaylor** [comment]
Could you provide a few examples of the movies it's not downloading the trailer for? I might be able to test locally and see exactly what's happening based on those titles.

**Comment by tripelbit-dev** [comment]
I sure can, here are a few files that are marked as "missing trailers" that say "done downloading" even though nothing gets added:

```
Y:\300 (2007)\300 (2007) - Bluray-2160p.x265.HDR.TrueHD Atmos.7.1.mkv
Y:\$5 a Day (2008)\$5 a Day (2008) - Bluray-720p.x264.DTS.5.1.mkv
Y:\Akira (1988)\Akira (1988) - Bluray-2160p.x265.HDR.TrueHD.5.1.mkv
Y:\American Beauty (1999)\American Beauty (1999) - HDTV-1080p.x264.DTS.5.1.mkv
Y:\Bad Trip (2020)\Bad Trip (2020) - WEBRip-1080p.x264.AAC.5.1.mkv
Y:\Mission Impossible III (2006)\Mission Impossible III (2006) - Bluray-2160p.x265.HDR.TrueHD.5.1.mkv
etc..
```

**Comment by taylorbobaylor** [comment]
It looks like these movies don't follow the **VERY** strict naming convention needed.
If you rename them like this it should work correctly:
```
Y:\300 (2007)\300 (2007).mkv
Y:\$5 a Day (2008)\$5 a Day (2008).mkv
```

**Comment by tripelbit-dev** [comment]
Ah I see, thanks for looking into it!

Quick suggestion, if the file name needs to match the folder name exactly, wouldn't it make sense to only use the folder's name to lookup the movie? Ignore the actual movie file name entirely. That way it would be easier to ensure you download the right trailer no matter what files are in the folder itself?

**Comment by taylorbobaylor** [comment]
It could probably work that way but some people might have different folder names compared to the files. I was just going off of how I have mine set in Radarr when I download my movies. One day I'd like to implement it to allow for different naming conventions etc but just need to find the time, hahaha!
