### ISSUE TITLE
Struggling to get this running on windows

### ISSUE THREAD

**Issue by jamescporter** [taylorbobaylor/TrailerDownloader#54]
Hi, I'm struggling to get this running on windows. This is the only output I get. Additionally, how can I set the target path?
![image](https://github.com/user-attachments/assets/01b3e85b-210c-4e63-bd0a-da15a39ec0eb)

**Comment by taylorbobaylor** [comment]
Hey there! So it looks like you have it running. In your browser go to http://localhost:5000 and it should bring you to the setup page where you put your media directory and preferred language.

**Comment by taylorbobaylor** [comment]
No problem!!

**Comment by taylorbobaylor** [comment]
Glad we could get it working, enjoy!!!
