### ISSUE TITLE
French ?

### ISSUE THREAD

**Issue by xZourSx** [taylorbobaylor/TrailerDownloader#7]
Hello

The software works very well however, would it be possible to have the trailers in French?

Thank you

**Comment by taylorbobaylor** [comment]
Hello!

Glad you're enjoying it. I'm using this to actually download the youtube trailers and I don't think there's a way to specify the download language.
https://github.com/Tyrrrz/YoutubeExplode

**Comment by taylorbobaylor** [comment]
Hey! I have updated so you can specify which language you want the trailers in on setup. Pull the latest docker image or use the .zip in the release section for windows and let me know if this works for you! There are some that it seems to not be able to find trailers for in certain languages but hopefully this helps!
Enjoy 😃
