### ISSUE TITLE
netowrk drive

### ISSUE THREAD

**Issue by wsolorza** [taylorbobaylor/TrailerDownloader#8]
I placed in my plex folder on my qnap accessing via windows 10 desktop but when I run the program cmd opens up but is blank

**Comment by taylorbobaylor** [comment]
Can you try running it from your Windows 10 desktop? It should load up then you can specify your network drive for your movies folder.

**Comment by CubeComming** [comment]
If you dont need to run the softwear on your windows pc you could use the docker version and deploy it directly on your qnap. This worked perfectly for my server (not a qnap).
