### ISSUE TITLE
Cronjobs and language Model?

### ISSUE THREAD

**Issue by CubeComming** [taylorbobaylor/TrailerDownloader#9]
I really like this softwear, its light and pretty fast. 

I just miss the possibility to change the trailer language. So instead if downloading english trailers i would love to download german ones. **(Well that was a dump question, as it had already been asked and it is not possible).** Or is it? (There seems to be some code for themoviedb which might open the possibility to add different language support).

I would also like it to run as a cronjob every x minutes. Is anything like that planed in the near future? 

Sadly as i run this programm in a docker container it deletes all data after stopping the container. Which Volume do i have to save locally for it to store these informations?

**Comment by taylorbobaylor** [comment]
Hey, glad you're enjoying it! 😃 

I've had a few requests for different languages and I'm not sure if it's possible since I'm using TMDB API to retrieve the YouTube link for the movie trailer and it seems pretty much all the links are for english.

I do plan to add a file system watcher and have it as a setting where it would automatically download the trailers for new movies you put in your library. I don't have an exact ETA on this unfortunately as work and life have been very slammed at the moment.

**Comment by CubeComming** [comment]
So i have done some research and if you use the following api call you get the youtube id for german trailers: (Here for the Minions).

`http://api.themoviedb.org/3/movie/211672/videos**?language=de-DE&**api_key=e438e2812f17faa299396505f2b375bb`

so adding a language variable which automatically fills the variable in the api call it should be possible to get language specific trailers.

**Comment by taylorbobaylor** [comment]
Great catch on TMDB api and specifying a language. I have added these changes to master and updated the docker image. Please try pulling the latest image and let me know if that works for you!

**Comment by CubeComming** [comment]
Sadly it doesn´t seem to work correct.

`fail: TrailerDownloader.SignalRHubs.MovieHub[0]

      Error downloading trailer for Minions

      Video watch page is broken.

      In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.

      To resolve this error, please wait some time and try again.

      If this issue persists, please report it on the project's GitHub page.` ~Logs

If i use the api call an add the movie id myself it seems to work perfektly, the youtube id is also not broken.
`https://api.themoviedb.org/3/movie/211672/videos?api_key=____&language=de-DE`
So it's probably either a mistake in getting the correct movie id or in getting the corecct youtube id.

I will try and have a look into it myself tomorrow, just letting you know.

**Comment by taylorbobaylor** [comment]
I will try and take a look tomorrow after work.
That error message is coming from the library package I'm using to actually download the YouTube trailers that can be found here. 

https://github.com/Tyrrrz/YoutubeExplode

**Comment by CubeComming** [comment]
Wonderful! :+1:

**Comment by taylorbobaylor** [comment]
I just tested and it was able to download the english and german trailer for Minions..... Can you provide more info on how to replicate this issue? What is your folder structure? Any additional logs etc?
Thank you! 😃

**Comment by CubeComming** [comment]
Strange....

Folder Strukture:

--Filme
->--Minions(2015)
->->--Minions(2015).mkv

In Docker the /movies Volume is pointed to /Filme and it loads them (mostly) sucessfully.

- Network: bridge
- Port: 6767:80
- Image: taylorbobaylor/movie-trailer-downloader:latest


I did nothing to the other settings.

**Comment by taylorbobaylor** [comment]
Hmmmmm 🤔 
Yeah port 6767:80 should be fine...
And in the logs of the container it says the same thing you posted above?

> ` fail: TrailerDownloader.SignalRHubs.MovieHub[0] Error downloading trailer for Minions Video watch page is broken. In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library. To resolve this error, please wait some time and try again. If this issue persists, please report it on the project's GitHub page.`
> 
> ~Logs

I'll try to do some more testing after work and see what we can find out.

**Comment by CubeComming** [comment]
Yes the log contains exactly this error message

**Comment by taylorbobaylor** [comment]
I just tested in a docker container with the same movie/structure and this is working for me.....

**Comment by CubeComming** [comment]
The Old version worked for me so it must be a problem with the new code. Could you please, if possible, make a container without the change in 

- TrailerDownloader/ClientApp/package-lock.json 
and in
-  .gitignore

Mabye the problem lies in these two files.

**Comment by taylorbobaylor** [comment]
The new code is what I've been testing with and seems to be working locally and in docker container... I will try to revert all changes after work and re-push.
https://hub.docker.com/r/taylorbobaylor/movie-trailer-downloader
I'm not having any issues accessing the docker hub in incognito or on different computers.
Sorry you're having issues and the new change wasn't working for you.

**Comment by CubeComming** [comment]
Ok I got the website working, I wasn't signed in correctly.

> Sorry you're having issues and the new change wasn't working for you.

We're here to solve that. And where would the fun be if it worked right away...

Thank you for your help.

Maybe you can push the new version with the reversed changes as a "experimental" version. That way we won't bother the other people, trying to solve the problem.

**Comment by taylorbobaylor** [comment]
For sure!

> Maybe you can push the new version with the reversed changes as a "experimental" version. That way we won't bother the other people, trying to solve the problem.
That sounds like a perfect plan. I'll revert those changes and make a new branch and docker image on my hug that you and I can test with as soon as I find the time.
Work is a bit crazy right now but I will try to do this as soon as I can. 😃

**Comment by CubeComming** [comment]
Wonderful :+1:

> Work is a bit crazy right now but I will try to do this as soon as I can. 😃

No pressure

**Comment by taylorbobaylor** [comment]
Whelp.... I had a very long, boring meeting so I actually got this done in a new branch. 😆 
I updated the nuget package "YoutubeExplode" that I'm using to actual download the trailers as well.
This is tested and working for me locally and inside a docker container on my server with all of my movies.
If this still isn't working for you we need to look at some other things I think.

Try to pull this image and let me know if that works!!!
https://hub.docker.com/repository/docker/taylorbobaylor/movie-trailer-downloader-language

**Comment by CubeComming** [comment]
nope still doesn't work. 
`TrailerDownloader.SignalRHubs.MovieHub[0]


      Error downloading trailer for Minions


      Video watch page is broken.


      In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.


      To resolve this error, please wait some time and try again.


      If this issue persists, please report it on the project's GitHub page.`
Did you roll it back all the way? Or partial?

**Comment by taylorbobaylor** [comment]
I can download your specific movie no issue and in german or english so it must be something different on your side.
I reverted the whole change for this image:
https://hub.docker.com/repository/docker/taylorbobaylor/movie-trailer-downloader

But this one is off the new branch testing out trailer languages:
https://hub.docker.com/repository/docker/taylorbobaylor/movie-trailer-downloader-language

**Comment by CubeComming** [comment]
I am so sorry I used the old image from here:
https://hub.docker.com/repository/docker/taylorbobaylor/movie-trailer-downloader
instead of the new experimental one from here:
https://hub.docker.com/repository/docker/taylorbobaylor/movie-trailer-downloader-language

this one works like a charm.. wonderful 👍

**Comment by taylorbobaylor** [comment]
Awesome!!!! So glad it's working for you 😃
